const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {DatabaseSync}=require('node:sqlite');
const {createServer}=require('../server');
const proposal={clientName:'Cliente',document:'12345678901',address:'Rua A',city:'Alfenas',state:'MG',moduleBrand:'Marca',moduleModel:'Modelo',modulePower:550,modules:6,inverterBrand:'Marca',inverterModel:'Modelo',inverterPower:3,inverterQuantity:1,investment:9000,installedKwp:3.3,annualGeneration:4600,annualSavings:4000};
test('contas, isolamento, migração, sessões, senha provisória e desativação',async t=>{
  const dir=path.join(__dirname,'../tmp','auth-test-'+crypto.randomUUID());fs.mkdirSync(dir,{recursive:true});
  const legacy=new DatabaseSync(path.join(dir,'contracts.sqlite'));
  legacy.exec('CREATE TABLE records(id TEXT PRIMARY KEY,token TEXT UNIQUE,body TEXT NOT NULL)');
  legacy.prepare('INSERT INTO records VALUES (?,?,?)').run('PT-LEGACY','legacy',JSON.stringify({id:'PT-LEGACY',proposal,status:'pending'}));legacy.close();
  let server=createServer({dataDir:dir});await new Promise(r=>server.listen(0,'127.0.0.1',r));
  t.after(()=>new Promise(r=>server.close(r)));
  let base='http://127.0.0.1:'+server.address().port;
  async function request(route,method='GET',data,cookie=''){
    const response=await fetch(base+'/api/'+route,{method,headers:{'Content-Type':'application/json',cookie},body:data?JSON.stringify(data):undefined});
    return {status:response.status,data:await response.json(),cookie:response.headers.get('set-cookie')?.split(';')[0],setCookie:response.headers.get('set-cookie')};
  }
  assert.equal((await request('auth/status')).data.needsSetup,true);
  const setup=await request('auth/setup','POST',{name:'Admin',email:'ADMIN@example.com',password:'admin-password-123'});
  assert.equal(setup.status,201);let admin=setup.cookie;const adminId=setup.data.user.id;
  assert.ok(!setup.setCookie.includes('Max-Age'));assert.ok(setup.setCookie.includes('HttpOnly'));
  assert.equal((await request('auth/setup','POST',{name:'Intruso',email:'bad@example.com',password:'password123'})).status,409);
  assert.equal((await request('login','POST',{password:'admin-password-123'})).status,401);
  assert.equal((await request('auth/status')).data.needsSetup,false);
  const legacyList=await request('records','GET',null,admin);assert.equal(legacyList.data[0].ownerId,adminId);
  const added=await request('users','POST',{name:'Vendedor A',email:'seller@example.com',password:'temporary-password',role:'seller'},admin);
  assert.equal(added.status,201);const sellerId=added.data.user.id;
  assert.equal((await request('users','POST',{name:'Duplicado',email:'SELLER@example.com',password:'temporary-password',role:'seller'},admin)).status,409);
  let login=await request('login','POST',{email:'SELLER@example.com',password:'temporary-password',remember:true});
  let seller=login.cookie;assert.equal(login.data.user.mustChangePassword,true);assert.ok(login.setCookie.includes('Max-Age=2592000'));
  assert.equal((await request('records','GET',null,seller)).status,403);
  const changed=await request('auth/password','POST',{currentPassword:'temporary-password',password:'seller-password-123',remember:true},seller);
  assert.equal(changed.status,200);const stale=seller;seller=changed.cookie;
  assert.ok(changed.setCookie.includes('Max-Age=2592000'));
  assert.equal((await request('auth/me','GET',null,stale)).status,401);
  assert.equal((await request('users','GET',null,seller)).status,403);
  assert.equal((await request('users','POST',{name:'Intruso',email:'x@example.com',password:'password1234',role:'admin'},seller)).status,403);
  assert.equal((await request('records','GET',null,seller)).data.length,0);
  const sellerRecord=(await request('records','POST',{proposal,ownerId:adminId},seller)).data;
  const sellerRows=(await request('records','GET',null,seller)).data;
  assert.equal(sellerRows.length,1);assert.equal(sellerRows[0].ownerId,sellerId);
  assert.equal((await request('records','GET',null,admin)).data.length,2);
  assert.equal((await request('records/PT-LEGACY/contract','PUT',{text:'alteração'},seller)).status,404);
  const second=await request('users','POST',{name:'Vendedor B',email:'b@example.com',password:'temporary-password',role:'seller'},admin);
  let b=(await request('login','POST',{email:'b@example.com',password:'temporary-password'})).cookie;
  b=(await request('auth/password','POST',{currentPassword:'temporary-password',password:'second-password-123'},b)).cookie;
  assert.equal((await request('records','GET',null,b)).data.length,0);
  assert.equal((await request('records/'+sellerRecord.id+'/contract','PUT',{text:'alteração'},b)).status,404);
  assert.equal((await request('users/'+adminId,'PATCH',{active:false},admin)).status,400);
  assert.equal((await request('users/'+sellerId,'PATCH',{active:false},admin)).status,200);
  assert.equal((await request('auth/me','GET',null,seller)).status,401);
  assert.equal((await request('login','POST',{email:'seller@example.com',password:'seller-password-123'})).status,401);
  await request('users/'+sellerId,'PATCH',{active:true,password:'reset-password-123'},admin);
  assert.equal((await request('login','POST',{email:'seller@example.com',password:'seller-password-123'})).status,401);
  assert.equal((await request('login','POST',{email:'seller@example.com',password:'reset-password-123'})).data.user.mustChangePassword,true);
  login=await request('login','POST',{email:'admin@example.com',password:'admin-password-123',remember:true});admin=login.cookie;
  await new Promise(r=>server.close(r));server=createServer({dataDir:dir});await new Promise(r=>server.listen(0,'127.0.0.1',r));base='http://127.0.0.1:'+server.address().port;
  assert.equal((await request('auth/me','GET',null,admin)).status,200);
  const db=new DatabaseSync(path.join(dir,'contracts.sqlite'));
  const stored=db.prepare('SELECT password_hash FROM users WHERE id=?').get(adminId).password_hash;
  assert.notEqual(stored,'admin-password-123');assert.ok(stored.includes(':'));
  assert.equal(db.prepare('SELECT count(*) n FROM sessions WHERE token_hash=?').get(admin.split('=')[1]).n,0);
  const expired=(await request('login','POST',{email:'b@example.com',password:'second-password-123'})).cookie;
  db.prepare('UPDATE sessions SET expires_at=0 WHERE user_id=?').run(second.data.user.id);
  assert.equal((await request('auth/me','GET',null,expired)).status,401);db.close();
  await request('logout','POST',null,admin);assert.equal((await request('auth/me','GET',null,admin)).status,401);
});
test('configuração inicial bloqueada quando o servidor está publicado',async t=>{
  const server=createServer({dataDir:path.join(__dirname,'../tmp','auth-public-'+crypto.randomUUID()),publicUrl:'https://solar.example'});
  await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>server.close(r)));
  const base='http://127.0.0.1:'+server.address().port;
  const response=await fetch(base+'/api/auth/setup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'Admin',email:'a@example.com',password:'long-password'})});
  assert.equal(response.status,403);
});
