const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const crypto=require('node:crypto');
const {createServer}=require('../server');
const Core=require('../contract-core');
const proposal={clientName:'Cliente Teste',document:'12345678901',address:'Rua Exemplo, 10',city:'Alfenas',state:'MG',moduleBrand:'Marca M',moduleModel:'Modelo M',modulePower:550,modules:6,inverterBrand:'Marca I',inverterModel:'Modelo I',inverterPower:3,inverterQuantity:1,investment:9572,installedKwp:3.3,annualGeneration:4600,annualSavings:4200,hsp:5.16,performance:.74,tariff:1.15};
const consent={name:'Cliente Teste',document:'12345678901',email:'cliente@example.com',confirmed:true};
const details={company:'Empresa Teste',companyDocument:'12345678000100',companyAddress:'Rua Comercial',representative:'Representante',engineer:'Engenheiro',utility:'Distribuidora',structure:'Telhado',payment:'80% + 20%',additional:'Nenhum',deadline:'60',meter:'Conforme distribuidora',jurisdiction:'Alfenas',date:'2026-09-27',backup:'Iluminação'};
const templateContext={window:{}};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../contract-template.js'),'utf8'),templateContext);
const template=templateContext.window.CONTRACT_TEMPLATE;
test('modelo remove dados do cliente original e preenche equipamentos e anexo',()=>{
  const record=Core.accept(proposal,{...consent,date:new Date().toISOString(),channel:'Link',evidence:'Registro'},'PT-TESTE');
  proposal.clientName='Nome alterado depois';assert.equal(record.proposal.clientName,'Cliente Teste');proposal.clientName='Cliente Teste';
  const text=Core.generate(record,details,template);
  assert.ok(text.includes('Marca M Modelo M'));assert.ok(text.includes('ANEXO B'));
  assert.ok(!text.includes('{{'));assert.ok(!text.includes('LIVIA NASCIMENTO'));assert.ok(!text.includes('BelCrad'));
  assert.ok(!text.includes('19 de junho de 2026'));assert.ok(!text.includes('068.651'));
  assert.throws(()=>Core.generate({proposal},details,template),/aceite/);
  const hybrid={...record,proposal:{...record.proposal,hybrid:true,batteryBrand:'Bateria',batteryModel:'Modelo B',batteryQuantity:2,storageCapacity:10.2,usableCapacity:9.18,autonomy:18.36,backupLoad:.5}};
  assert.ok(Core.generate(hybrid,details,template).includes('Escopo dos circuitos de backup: Iluminação'));
});
test('API: autenticação, aceite, revisão, assinatura imutável e persistência',async t=>{
  const dataDir=path.join(__dirname,'../tmp','contracts-test-'+crypto.randomUUID());
  let server=createServer({dataDir,password:'test-only-password'});
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  t.after(()=>new Promise(resolve=>server.close(resolve)));
  let base='http://127.0.0.1:'+server.address().port,cookie='';
  async function request(route,method='GET',data,admin=false){
    const response=await fetch(base+route,{method,headers:{'Content-Type':'application/json',...(admin?{cookie}:{})},body:data?JSON.stringify(data):undefined});
    return {status:response.status,data:await response.json(),cookie:response.headers.get('set-cookie')?.split(';')[0]};
  }
  assert.equal((await request('/api/records')).status,401);
  assert.equal((await request('/api/login','POST',{password:'wrong'})).status,401);
  cookie=(await request('/api/login','POST',{password:'test-only-password'})).cookie;
  const created=await request('/api/records','POST',{proposal},true);assert.equal(created.status,201);
  const id=created.data.id,token=created.data.publicPath.split('#')[1],url='/api/public/'+token;
  assert.equal((await request('/api/public/'+'x'.repeat(43))).status,404);
  assert.equal((await request('/api/records/'+id+'/contract','PUT',{text:'Prematuro',details,reviewed:true,previousRevision:0},true)).status,409);
  assert.equal((await request(url+'/accept','POST',{...consent,confirmed:false})).status,400);
  assert.equal((await request(url+'/accept','POST',{...consent,document:'99999999999'})).status,400);
  const accepts=await Promise.all([request(url+'/accept','POST',consent),request(url+'/accept','POST',consent)]);
  assert.deepEqual(accepts.map(r=>r.status).sort(),[200,409]);
  let saved=(await request('/api/records','GET',null,true)).data[0];
  const text=Core.generate(saved,details,template);
  const published=await request('/api/records/'+id+'/contract','PUT',{text,details,reviewed:true,previousRevision:0},true);
  assert.equal(published.status,200);
  assert.equal((await request('/api/records/'+id+'/contract','PUT',{text,details,reviewed:true,previousRevision:0},true)).status,409);
  const publicRecord=(await request(url)).data;
  assert.ok(!('kitCost' in publicRecord.proposal));assert.ok(!('acceptance' in publicRecord));
  assert.equal((await request(url+'/sign','POST',{...consent,hash:'outdated'})).status,409);
  const signed=await request(url+'/sign','POST',{...consent,hash:publicRecord.contract.hash});assert.equal(signed.status,200);
  assert.equal((await request(url+'/sign','POST',{...consent,hash:publicRecord.contract.hash})).status,409);
  assert.equal((await request('/api/records/'+id+'/contract','PUT',{text:'Mudança',details,reviewed:true,previousRevision:1},true)).status,409);
  assert.equal((await request('/.data/admin-key.txt')).status,404);
  const crossOrigin=await fetch(base+'/api/records',{method:'POST',headers:{'Content-Type':'application/json',cookie,Origin:'https://example.com'},body:JSON.stringify({proposal})});
  assert.equal(crossOrigin.status,403);
  await new Promise(resolve=>server.close(resolve));
  server=createServer({dataDir,password:'test-only-password'});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  base='http://127.0.0.1:'+server.address().port;
  const persisted=(await request(url)).data;assert.equal(persisted.status,'signed');
  assert.equal(persisted.signature.hash,crypto.createHash('sha256').update(text).digest('hex'));
  assert.equal(persisted.events.length,2);
});
